[package]
name = "caps"
version = "0.0.2-pre"
authors = ["Luca Bruno <lucab@debian.org>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/lucab/caps-rs"
documentation = "https://docs.rs/caps"
description = "A pure-Rust library to work with Linux capabilities"
keywords = ["Linux", "capabilities", "POSIX", "getcap", "setcap"]
exclude = [
".gitignore",
".travis.yml",
]

[dependencies]
libc = "0.2"
error-chain = {version = "0.9", default-features = false}
enum_derive = "0.1"
custom_derive ="0.1"
